export const DEFAULT_CHAT_PAGE_SIZE = 30;
export const DEFAULT_CHAT_BOTTOM_OFFSET = 200;
export const DEFAULT_CHAT_SCROLL_BOTTOM_DURATION = 500;
export const DEFAULT_CHAT_MAX_BLOCK_TIME_DIFFERENCE = 3; // in minutes
