package com.example.fintrack;

import com.example.fintrack.bill.Bill;
import com.example.fintrack.bill.BillRepository;
import com.example.fintrack.category.Category;
import com.example.fintrack.category.CategoryRepository;
import com.example.fintrack.chat.Chat;
import com.example.fintrack.chat.ChatRepository;
import com.example.fintrack.friend.FriendStatus;
import com.example.fintrack.lastreadmessage.LastReadMessage;
import com.example.fintrack.lastreadmessage.LastReadMessageRepository;
import com.example.fintrack.limit.Limit;
import com.example.fintrack.limit.LimitRepository;
import com.example.fintrack.currency.Currency;
import com.example.fintrack.currency.CurrencyRepository;
import com.example.fintrack.event.Event;
import com.example.fintrack.event.EventRepository;
import com.example.fintrack.message.Message;
import com.example.fintrack.message.MessageRepository;
import com.example.fintrack.message.MessageType;
import com.example.fintrack.userevent.UserEvent;
import com.example.fintrack.userevent.UserEventRepository;
import com.example.fintrack.friend.Friend;
import com.example.fintrack.friend.FriendRepository;
import com.example.fintrack.rate.Rate;
import com.example.fintrack.rate.RateRepository;
import com.example.fintrack.user.User;
import com.example.fintrack.user.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final PasswordEncoder passwordEncoder;
    private final LimitRepository limitRepository;
    private final CurrencyRepository currencyRepository;
    private final RateRepository rateRepository;
    private final UserRepository userRepository;
    private final CategoryRepository categoryRepository;
    private final EventRepository eventRepository;
    private final UserEventRepository userEventRepository;
    private final BillRepository billRepository;
    private final FriendRepository friendRepository;
    private final ChatRepository chatRepository;
    private final MessageRepository messageRepository;
    private final LastReadMessageRepository lastReadMessageRepository;

    @Override
    public void run(String... args) {
        Currency currency1 = new Currency();
        currency1.setName("Złoty polski");
        currency1.setCode("PLN");
        Currency currency2 = new Currency();
        currency2.setName("Euro");
        currency2.setCode("EUR");
        Currency currency3 = new Currency();
        currency3.setName("Dolar amerykański");
        currency3.setCode("USD");
        Currency currency4 = new Currency();
        currency4.setName("Funt szterling");
        currency4.setCode("GBP");
        Currency currency5 = new Currency();
        currency5.setName("Frank szwajcarski");
        currency5.setCode("CHF");
        Currency currency6 = new Currency();
        currency6.setName("Korona czeska");
        currency6.setCode("CZK");
        currencyRepository.saveAll(List.of(currency1, currency2, currency3, currency4, currency5, currency6));

        Rate rate1 = new Rate();
        rate1.setDate(ZonedDateTime.now());
        rate1.setCurrency(currency1);
        rate1.setAmount(BigDecimal.valueOf(3.7479));
        Rate rate2 = new Rate();
        rate2.setDate(ZonedDateTime.now());
        rate2.setCurrency(currency2);
        rate2.setAmount(BigDecimal.valueOf(0.8836));
        Rate rate3 = new Rate();
        rate3.setDate(ZonedDateTime.now());
        rate3.setCurrency(currency3);
        rate3.setAmount(BigDecimal.valueOf(1));
        Rate rate4 = new Rate();
        rate4.setDate(ZonedDateTime.now());
        rate4.setCurrency(currency4);
        rate4.setAmount(BigDecimal.valueOf(0.7421));
        Rate rate5 = new Rate();
        rate5.setDate(ZonedDateTime.now());
        rate5.setCurrency(currency5);
        rate5.setAmount(BigDecimal.valueOf(0.8274));
        Rate rate6 = new Rate();
        rate6.setDate(ZonedDateTime.now());
        rate6.setCurrency(currency6);
        rate6.setAmount(BigDecimal.valueOf(22.0220));
        rateRepository.saveAll(List.of(rate1, rate2, rate3, rate4, rate5, rate6));

        User user1 = new User();
        user1.setFirstName("abc");
        user1.setLastName("def");
        user1.setEmail("abc@def.com");
        user1.setLastSeenAt(ZonedDateTime.now().minusMinutes(25));
        user1.setPassword(passwordEncoder.encode("password"));
        user1.setCurrency(currency1);
        User user2 = new User();
        user2.setFirstName("qwe");
        user2.setLastName("zxc");
        user2.setEmail("qwe@zxc.com");
        user2.setLastSeenAt(ZonedDateTime.now().minusMinutes(30));
        user2.setPassword(passwordEncoder.encode("password"));
        user2.setCurrency(currency1);
        User user3 = new User();
        user3.setFirstName("asd");
        user3.setLastName("qwe");
        user3.setEmail("asd@qwe.com");
        user3.setLastSeenAt(ZonedDateTime.now().minusMinutes(12));
        user3.setPassword(passwordEncoder.encode("password"));
        user3.setCurrency(currency2);
        userRepository.saveAll(List.of(user1, user2, user3));

        Chat chat1 = new Chat();
        chat1.setIsStarted(true);
        Chat chat2 = new Chat();
        chat2.setIsStarted(false);
        Chat chat3 = new Chat();
        chat3.setIsStarted(true);
        Chat chat4 = new Chat();
        chat4.setIsStarted(true);
        Chat chat5 = new Chat();
        chat5.setIsStarted(true);
        chatRepository.saveAll(List.of(chat1, chat2, chat3, chat4, chat5));

        Friend friend1 = new Friend();
        friend1.setUser(user1);
        friend1.setFriend(user2);
        friend1.setCreatedAt(ZonedDateTime.now().minusDays(1).minusHours(2));
        friend1.setFriendStatus(FriendStatus.ACCEPTED);
        friend1.setChat(chat1);
        Friend friend2 = new Friend();
        friend2.setUser(user1);
        friend2.setFriend(user3);
        friend2.setCreatedAt(ZonedDateTime.now().minusHours(2));
        friend2.setFriendStatus(FriendStatus.REQUESTED);
        friend2.setChat(chat2);
        Friend friend3 = new Friend();
        friend3.setUser(user2);
        friend3.setFriend(user1);
        friend3.setCreatedAt(ZonedDateTime.now().minusDays(1).minusHours(2));
        friend3.setFriendStatus(FriendStatus.ACCEPTED);
        friend3.setChat(chat1);
        Friend friend4 = new Friend();
        friend4.setUser(user3);
        friend4.setFriend(user1);
        friend4.setCreatedAt(ZonedDateTime.now().minusHours(2));
        friend4.setFriendStatus(FriendStatus.PENDING);
        friend4.setChat(chat2);
        friendRepository.saveAll(List.of(friend1, friend2, friend3, friend4));

        Category category1 = new Category();
        category1.setName("Ogólne");
        category1.setColor("#B1A8B3");
        category1.setUser(user1);
        category1.setIsDefault(true);
        Category category2 = new Category();
        category2.setUser(user1);
        category2.setName("Wydarzenie");
        category2.setColor("#666A63");
        category2.setIsDefault(true);
        Category category3 = new Category();
        category3.setName("Ogólne");
        category3.setColor("#B1A8B3");
        category3.setUser(user2);
        category3.setIsDefault(true);
        Category category4 = new Category();
        category4.setUser(user2);
        category4.setName("Wydarzenie");
        category4.setColor("#666A63");
        category4.setIsDefault(true);
        Category category5 = new Category();
        category5.setName("Ogólne");
        category5.setColor("#B1A8B3");
        category5.setUser(user3);
        category5.setIsDefault(true);
        Category category6 = new Category();
        category6.setUser(user3);
        category6.setName("Wydarzenie");
        category6.setColor("#666A63");
        category6.setIsDefault(true);
        Category category7 = new Category();
        category7.setName("Zakupy spożywcze");
        category7.setColor("#42FF81");
        category7.setUser(user1);
        category7.setIsDefault(false);
        Category category8 = new Category();
        category8.setName("Samochód");
        category8.setColor("#EF2727");
        category8.setUser(user1);
        category8.setIsDefault(false);
        Category category9 = new Category();
        category9.setName("Odzież");
        category9.setColor("#423E43");
        category9.setUser(user1);
        category9.setIsDefault(false);
        Category category10 = new Category();
        category10.setName("Mieszkanie");
        category10.setColor("#C1F308");
        category10.setUser(user2);
        category10.setIsDefault(false);
        Category category11 = new Category();
        category11.setName("Zakupy spożywcze");
        category11.setColor("#DEA910");
        category11.setUser(user2);
        category11.setIsDefault(false);
        Category category12 = new Category();
        category12.setName("Odzież");
        category12.setColor("#F9D7E3");
        category12.setUser(user3);
        category12.setIsDefault(false);
        categoryRepository.saveAll(List.of(category1, category2, category3, category4, category5, category6,
                category7, category8, category9, category10, category11, category12));

        Limit limit1 = new Limit();
        limit1.setAmount(BigDecimal.valueOf(500));
        limit1.setCategory(category1);
        limit1.setStartDateTime(ZonedDateTime.now());
        Limit limit2 = new Limit();
        limit2.setAmount(BigDecimal.valueOf(400));
        limit2.setCategory(category2);
        limit2.setStartDateTime(ZonedDateTime.now());
        Limit limit3 = new Limit();
        limit3.setAmount(BigDecimal.valueOf(800));
        limit3.setCategory(category4);
        limit3.setStartDateTime(ZonedDateTime.now());
        Limit limit4 = new Limit();
        limit4.setAmount(BigDecimal.valueOf(300));
        limit4.setCategory(category5);
        limit4.setStartDateTime(ZonedDateTime.now());
        Limit limit5 = new Limit();
        limit5.setAmount(BigDecimal.valueOf(400));
        limit5.setCategory(category6);
        limit5.setStartDateTime(ZonedDateTime.now());
        limitRepository.saveAll(List.of(limit1, limit2, limit3, limit4, limit5));

        Event event1 = new Event();
        event1.setName("Wycieczka do Niemiec");
        event1.setCurrency(currency1);
        event1.setStartDateTime(ZonedDateTime.now().minusDays(2));
        event1.setChat(chat3);
        Event event2 = new Event();
        event2.setName("Prezent urodzinowy");
        event2.setCurrency(currency1);
        event2.setStartDateTime(ZonedDateTime.now().plusDays(1).plusHours(4));
        event2.setChat(chat4);
        Event event3 = new Event();
        event3.setName("Wycieczka do Warszawy");
        event3.setCurrency(currency2);
        event3.setStartDateTime(ZonedDateTime.now().minusHours(5));
        event3.setChat(chat5);
        eventRepository.saveAll(List.of(event1, event2, event3));

        UserEvent userEvent1 = new UserEvent();
        userEvent1.setIsFounder(true);
        userEvent1.setUser(user1);
        userEvent1.setEvent(event1);
        UserEvent userEvent2 = new UserEvent();
        userEvent2.setIsFounder(false);
        userEvent2.setUser(user2);
        userEvent2.setEvent(event1);
        UserEvent userEvent3 = new UserEvent();
        userEvent3.setIsFounder(false);
        userEvent3.setUser(user3);
        userEvent3.setEvent(event1);
        UserEvent userEvent4 = new UserEvent();
        userEvent4.setIsFounder(true);
        userEvent4.setUser(user1);
        userEvent4.setEvent(event2);
        UserEvent userEvent5 = new UserEvent();
        userEvent5.setIsFounder(false);
        userEvent5.setUser(user2);
        userEvent5.setEvent(event2);
        UserEvent userEvent6 = new UserEvent();
        userEvent6.setIsFounder(true);
        userEvent6.setUser(user2);
        userEvent6.setEvent(event3);
        UserEvent userEvent7 = new UserEvent();
        userEvent7.setIsFounder(false);
        userEvent7.setUser(user3);
        userEvent7.setEvent(event3);
        userEventRepository.saveAll(List.of(userEvent1, userEvent2, userEvent3, userEvent4, userEvent5, userEvent6, userEvent7));

        Message message1 = new Message();
        message1.setChat(chat1);
        message1.setMessageType(MessageType.USER);
        message1.setSendTime(ZonedDateTime.now().minusHours(2).minusMinutes(8));
        message1.setContent("Cześć");
        message1.setSentBy(user1);
        Message message2 = new Message();
        message2.setChat(chat1);
        message2.setMessageType(MessageType.USER);
        message2.setSendTime(ZonedDateTime.now().minusHours(1).minusMinutes(5));
        message2.setContent("Dzień dobry");
        message2.setSentBy(user2);
        messageRepository.saveAll(List.of(message1, message2));

        LastReadMessage lastReadMessage1 = new LastReadMessage();
        lastReadMessage1.setMessage(message2);
        lastReadMessage1.setReadTime(ZonedDateTime.now().minusHours(2).minusMinutes(24));
        lastReadMessage1.setChat(chat1);
        lastReadMessage1.setUser(user1);
        LastReadMessage lastReadMessage2 = new LastReadMessage();
        lastReadMessage2.setMessage(message2);
        lastReadMessage2.setReadTime(ZonedDateTime.now().minusHours(1).minusMinutes(5));
        lastReadMessage2.setChat(chat1);
        lastReadMessage2.setUser(user2);
        lastReadMessageRepository.saveAll(List.of(lastReadMessage1, lastReadMessage2));

        Bill bill1 = new Bill();
        bill1.setName("Restauracja");
        bill1.setDate(ZonedDateTime.now().minusDays(12));
        bill1.setCategory(category1);
        bill1.setCurrency(currency1);
        bill1.setUser(user1);
        bill1.setAmount(BigDecimal.valueOf(56));
        Bill bill2 = new Bill();
        bill2.setName("Paliwo");
        bill2.setDate(ZonedDateTime.now().minusDays(10).minusHours(10));
        bill2.setCategory(category7);
        bill2.setCurrency(currency1);
        bill2.setUser(user1);
        bill2.setAmount(BigDecimal.valueOf(153));
        Bill bill3 = new Bill();
        bill3.setName("Taxi");
        bill3.setDate(ZonedDateTime.now().minusDays(8).minusHours(6));
        bill3.setCategory(category2);
        bill3.setCurrency(currency1);
        bill3.setEvent(event1);
        bill3.setPaidBy(user1);
        bill3.setAmount(BigDecimal.valueOf(124));
        Bill bill4 = new Bill();
        bill4.setName("Bilety");
        bill4.setDate(ZonedDateTime.now().minusDays(7).minusHours(2));
        bill4.setCategory(category2);
        bill4.setCurrency(currency1);
        bill4.setEvent(event2);
        bill4.setPaidBy(user1);
        bill4.setAmount(BigDecimal.valueOf(98));
        Bill bill5 = new Bill();
        bill5.setName("Pizza");
        bill5.setDate(ZonedDateTime.now().minusDays(5).minusHours(15));
        bill5.setCategory(category10);
        bill5.setCurrency(currency1);
        bill5.setUser(user2);
        bill5.setAmount(BigDecimal.valueOf(202));
        Bill bill6 = new Bill();
        bill6.setName("Ziemniaki");
        bill6.setDate(ZonedDateTime.now().minusDays(3).minusHours(3));
        bill6.setCategory(category12);
        bill6.setCurrency(currency1);
        bill6.setUser(user3);
        bill6.setAmount(BigDecimal.valueOf(51));
        Bill bill7 = new Bill();
        bill7.setName("Woda");
        bill7.setDate(ZonedDateTime.now().minusDays(6).minusHours(18));
        bill7.setCategory(category4);
        bill7.setCurrency(currency1);
        bill7.setEvent(event1);
        bill7.setPaidBy(user2);
        bill7.setAmount(BigDecimal.valueOf(104));
        Bill bill8 = new Bill();
        bill8.setName("Woda");
        bill8.setDate(ZonedDateTime.now().minusDays(1).minusHours(16));
        bill8.setCategory(category6);
        bill8.setCurrency(currency1);
        bill8.setEvent(event1);
        bill8.setPaidBy(user3);
        bill8.setAmount(BigDecimal.valueOf(50));
        Bill bill9 = new Bill();
        bill9.setName("Komputer");
        bill9.setDate(ZonedDateTime.now().minusDays(1).minusHours(6));
        bill9.setCategory(category7);
        bill9.setCurrency(currency2);
        bill9.setUser(user1);
        bill9.setAmount(BigDecimal.valueOf(75));
        Bill bill10 = new Bill();
        bill10.setName("Obiad");
        bill10.setDate(ZonedDateTime.now().minusDays(5).minusHours(22));
        bill10.setCategory(category7);
        bill10.setCurrency(currency2);
        bill10.setUser(user1);
        bill10.setAmount(BigDecimal.valueOf(88));
        Bill bill11 = new Bill();
        bill11.setName("Telefon");
        bill11.setDate(ZonedDateTime.now().minusHours(12));
        bill11.setCategory(category7);
        bill11.setCurrency(currency2);
        bill11.setUser(user1);
        bill11.setAmount(BigDecimal.valueOf(245));
        Bill bill12 = new Bill();
        bill12.setName("Ubrania");
        bill12.setDate(ZonedDateTime.now().plusDays(2));
        bill12.setCategory(category1);
        bill12.setCurrency(currency2);
        bill12.setUser(user1);
        bill12.setAmount(BigDecimal.valueOf(215));
        Bill bill13 = new Bill();
        bill13.setName("Myszka");
        bill13.setDate(ZonedDateTime.now().plusDays(3).plusHours(4));
        bill13.setCategory(category2);
        bill13.setCurrency(currency2);
        bill13.setUser(user1);
        bill13.setAmount(BigDecimal.valueOf(133));
        Bill bill14 = new Bill();
        bill14.setName("Papryka");
        bill14.setDate(ZonedDateTime.now().plusDays(5).plusHours(6));
        bill14.setCategory(category2);
        bill14.setCurrency(currency2);
        bill14.setUser(user1);
        bill14.setAmount(BigDecimal.valueOf(13));
        billRepository.saveAll(List.of(bill1, bill2, bill3, bill4, bill5, bill6, bill7, bill8, bill9, bill10, bill11, bill12, bill13, bill14));
    }
}
