package com.example.fintrack;

import com.example.fintrack.bill.Bill;
import com.example.fintrack.bill.BillRepository;
import com.example.fintrack.category.Category;
import com.example.fintrack.category.CategoryRepository;
import com.example.fintrack.category.Limit;
import com.example.fintrack.category.LimitRepository;
import com.example.fintrack.currency.Currency;
import com.example.fintrack.currency.CurrencyRepository;
import com.example.fintrack.event.Event;
import com.example.fintrack.event.EventRepository;
import com.example.fintrack.event.UserEvent;
import com.example.fintrack.event.UserEventRepository;
import com.example.fintrack.friend.Friend;
import com.example.fintrack.friend.FriendRepository;
import com.example.fintrack.order.Order;
import com.example.fintrack.order.OrderRepository;
import com.example.fintrack.payment.Payment;
import com.example.fintrack.payment.PaymentRepository;
import com.example.fintrack.user.User;
import com.example.fintrack.user.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final PasswordEncoder passwordEncoder;
    private final LimitRepository limitRepository;
    private final CurrencyRepository currencyRepository;
    private final UserRepository userRepository;
    private final CategoryRepository categoryRepository;
    private final EventRepository eventRepository;
    private final UserEventRepository userEventRepository;
    private final BillRepository billRepository;
    private final OrderRepository orderRepository;
    private final PaymentRepository paymentRepository;
    private final FriendRepository friendRepository;

    @Override
    public void run(String... args) {
        Currency currency1 = new Currency();
        currency1.setName("PLN");
        Currency currency2 = new Currency();
        currency2.setName("EUR");
        Currency currency3 = new Currency();
        currency3.setName("USD");
        Currency currency4 = new Currency();
        currency4.setName("GBP");
        currencyRepository.saveAll(List.of(currency1, currency2, currency3, currency4));

        User user1 = new User();
        user1.setFirstName("abc");
        user1.setLastName("def");
        user1.setEmail("abc@def.com");
        user1.setPassword(passwordEncoder.encode("password"));
        user1.setCurrency(currency1);
        User user2 = new User();
        user2.setFirstName("qwe");
        user2.setLastName("zxc");
        user2.setEmail("qwe@zxc.com");
        user2.setPassword(passwordEncoder.encode("password"));
        user2.setCurrency(currency1);
        User user3 = new User();
        user3.setFirstName("asd");
        user3.setLastName("qwe");
        user3.setEmail("asd@qwe.com");
        user3.setPassword(passwordEncoder.encode("password"));
        user3.setCurrency(currency2);
        userRepository.saveAll(List.of(user1, user2, user3));

        Friend friend1 = new Friend();
        friend1.setUser(user1);
        friend1.setFriend(user2);
        friend1.setAccepted(true);
        Friend friend2 = new Friend();
        friend2.setUser(user1);
        friend2.setFriend(user3);
        friend2.setAccepted(true);
        Friend friend3 = new Friend();
        friend3.setUser(user2);
        friend3.setFriend(user1);
        friend3.setAccepted(true);
        Friend friend4 = new Friend();
        friend4.setUser(user3);
        friend4.setFriend(user1);
        friend4.setAccepted(true);
        friendRepository.saveAll(List.of(friend1, friend2, friend3, friend4));

        Category category1 = new Category();
        category1.setName("Groceries");
        category1.setColor("#42FF81");
        category1.setUser(user1);
        Category category2 = new Category();
        category2.setName("Car");
        category2.setColor("#EF2727");
        category2.setUser(user1);
        Category category3 = new Category();
        category3.setName("Clothing");
        category3.setColor("#423E43");
        category3.setUser(user1);
        Category category4 = new Category();
        category4.setName("Flat");
        category4.setColor("#C1F308");
        category4.setUser(user2);
        Category category5 = new Category();
        category5.setName("Groceries");
        category5.setColor("#DEA910");
        category5.setUser(user2);
        Category category6 = new Category();
        category6.setName("Clothing");
        category6.setColor("#F9D7E3");
        category6.setUser(user3);
        categoryRepository.saveAll(List.of(category1, category2, category3, category4, category5, category6));

        Limit limit1 = new Limit();
        limit1.setValue(new BigDecimal("500"));
        limit1.setCategory(category1);
        limit1.setStartDateTime(LocalDateTime.now());
        Limit limit2 = new Limit();
        limit2.setValue(new BigDecimal("400"));
        limit2.setCategory(category2);
        limit2.setStartDateTime(LocalDateTime.now());
        Limit limit3 = new Limit();
        limit3.setValue(new BigDecimal("500"));
        limit3.setCategory(category3);
        limit3.setStartDateTime(LocalDateTime.now());
        Limit limit4 = new Limit();
        limit4.setValue(new BigDecimal("800"));
        limit4.setCategory(category4);
        limit4.setStartDateTime(LocalDateTime.now());
        Limit limit5 = new Limit();
        limit5.setValue(new BigDecimal("300"));
        limit5.setCategory(category5);
        limit5.setStartDateTime(LocalDateTime.now());
        Limit limit6 = new Limit();
        limit6.setValue(new BigDecimal("400"));
        limit6.setCategory(category6);
        limit6.setStartDateTime(LocalDateTime.now());
        limitRepository.saveAll(List.of(limit1, limit2, limit3, limit4, limit5, limit6));

        Event event1 = new Event();
        event1.setName("Germany trip");
        event1.setCurrency(currency1);
        event1.setStartDateTime(LocalDateTime.now());
        Event event2 = new Event();
        event2.setName("Birthday gift");
        event2.setCurrency(currency1);
        event2.setStartDateTime(LocalDateTime.now());
        Event event3 = new Event();
        event3.setName("Warsaw trip");
        event3.setCurrency(currency2);
        event3.setStartDateTime(LocalDateTime.now());
        eventRepository.saveAll(List.of(event1, event2, event3));

        UserEvent userEvent1 = new UserEvent();
        userEvent1.setIsOwner(true);
        userEvent1.setUser(user1);
        userEvent1.setEvent(event1);
        UserEvent userEvent2 = new UserEvent();
        userEvent2.setIsOwner(false);
        userEvent2.setUser(user2);
        userEvent2.setEvent(event1);
        UserEvent userEvent3 = new UserEvent();
        userEvent3.setIsOwner(false);
        userEvent3.setUser(user3);
        userEvent3.setEvent(event1);
        UserEvent userEvent4 = new UserEvent();
        userEvent4.setIsOwner(true);
        userEvent4.setUser(user1);
        userEvent4.setEvent(event2);
        UserEvent userEvent5 = new UserEvent();
        userEvent5.setIsOwner(false);
        userEvent5.setUser(user2);
        userEvent5.setEvent(event2);
        UserEvent userEvent6 = new UserEvent();
        userEvent6.setIsOwner(true);
        userEvent6.setUser(user2);
        userEvent6.setEvent(event3);
        UserEvent userEvent7 = new UserEvent();
        userEvent7.setIsOwner(false);
        userEvent7.setUser(user3);
        userEvent7.setEvent(event3);
        userEventRepository.saveAll(List.of(userEvent1, userEvent2, userEvent3, userEvent4, userEvent5, userEvent6, userEvent7));

        Bill bill1 = new Bill();
        bill1.setName("Restaurant");
        bill1.setDate(LocalDateTime.now());
        bill1.setCategory(category1);
        bill1.setCurrency(currency1);
        bill1.setUser(user1);
        Bill bill2 = new Bill();
        bill2.setName("Fuel");
        bill2.setDate(LocalDateTime.now());
        bill2.setCategory(category2);
        bill2.setCurrency(currency1);
        bill2.setUser(user1);
        Bill bill3 = new Bill();
        bill3.setName("Taxi");
        bill3.setDate(LocalDateTime.now());
        bill3.setCategory(category2);
        bill3.setCurrency(currency1);
        bill3.setEvent(event1);
        Bill bill4 = new Bill();
        bill4.setName("Tickets");
        bill4.setDate(LocalDateTime.now());
        bill4.setCategory(category3);
        bill4.setCurrency(currency1);
        bill4.setEvent(event2);
        Bill bill5 = new Bill();
        bill5.setName("Pizza");
        bill5.setDate(LocalDateTime.now());
        bill5.setCategory(category4);
        bill5.setCurrency(currency1);
        bill5.setUser(user2);
        Bill bill6 = new Bill();
        bill6.setName("Potatoes");
        bill6.setDate(LocalDateTime.now());
        bill6.setCategory(category4);
        bill6.setCurrency(currency1);
        bill6.setUser(user3);
        billRepository.saveAll(List.of(bill1, bill2, bill3, bill4, bill5, bill6));

        Order order1 = new Order();
        order1.setValue(BigDecimal.valueOf(100));
        order1.setBill(bill1);
        order1.setUser(user1);
        Order order2 = new Order();
        order2.setValue(BigDecimal.valueOf(300));
        order2.setBill(bill2);
        order2.setUser(user1);
        Order order3 = new Order();
        order3.setValue(BigDecimal.valueOf(200));
        order3.setBill(bill3);
        order3.setUser(user1);
        Order order4 = new Order();
        order4.setValue(BigDecimal.valueOf(400));
        order4.setBill(bill4);
        order4.setUser(user2);
        Order order5 = new Order();
        order5.setValue(BigDecimal.valueOf(100));
        order5.setBill(bill5);
        order5.setUser(user2);
        Order order6 = new Order();
        order6.setValue(BigDecimal.valueOf(100));
        order6.setBill(bill6);
        order6.setUser(user3);
        orderRepository.saveAll(List.of(order1, order2, order3, order4, order5, order6));

        Payment payment1 = new Payment();
        payment1.setAmount(BigDecimal.valueOf(100));
        payment1.setBill(bill1);
        payment1.setUser(user1);
        Payment payment2 = new Payment();
        payment2.setAmount(BigDecimal.valueOf(200));
        payment2.setBill(bill2);
        payment2.setUser(user1);
        Payment payment3 = new Payment();
        payment3.setAmount(BigDecimal.valueOf(400));
        payment3.setBill(bill3);
        payment3.setUser(user1);
        Payment payment4 = new Payment();
        payment4.setAmount(BigDecimal.valueOf(300));
        payment4.setBill(bill4);
        payment4.setUser(user2);
        Payment payment5 = new Payment();
        payment5.setAmount(BigDecimal.valueOf(200));
        payment5.setBill(bill5);
        payment5.setUser(user2);
        Payment payment6 = new Payment();
        payment6.setAmount(BigDecimal.valueOf(300));
        payment6.setBill(bill6);
        payment6.setUser(user3);
        paymentRepository.saveAll(List.of(payment1, payment2, payment3, payment4, payment5, payment6));
    }
}
