export enum ApiErrorCode {
  NO_CODE = 0,
  INVALID_TOKEN = 100,
  ACCESS_TOKEN_EXPIRED = 300,
  VERIFICATION_CODE_EXPIRED = 301,
  BAD_CREDENTIALS = 302,
  ALREADY_EXISTS = 303,
  INVALID_USER = 304,
  CURRENCY_NOT_FOUND = 305,
  INTERNAL_SERVER_ERROR = 306,
}
