name: Docker Containerization

on:
  push:
    branches: ["master", "workflows-dev"]
    paths:
      - "front/**"
      - "backend/**"
      - "**/docker-compose.yml"
  pull_request:
    branches: ["master", "workflows-dev"]
    paths:
      - "front/**"
      - "backend/**"
      - "**/docker-compose.yml"
  workflow_dispatch:

jobs:
  Build:
    name: Compose-up
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build containers
        uses: hoverkraft-tech/compose-action@v2.2.0
